### ISSUE TITLE
[Ref] : MVVM Project 생성 + 폴더링

### ISSUE THREAD

**Issue by SeorinY** [31st-IN-SOPT-iOS-Part/Seorin#2]
MVVM Project 생성
RxSwift 사용해서 세미나 과제 해볼게요!

**Comment by cchanmi** [comment]
굳굳 ㅎㅎㅎ 👍👍

기존의 코드에서 리팩토링하는 작업이기 때문에
이슈 제목을 [Feat]이 아닌 [Refactor]로 작성하는 것이 더 맞을 것 같네요!

**Comment by SeorinY** [comment]
피드백 너무 감사합니당 🥹
